"""
Core data types for the trading system.
All types use dataclasses for clarity and immutability where appropriate.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional
from enum import Enum, auto
import pytz


class SignalDirection(Enum):
    """Direction of a trading signal."""
    LONG = auto()
    SHORT = auto()
    NEUTRAL = auto()


class OrderType(Enum):
    """Order execution type."""
    MARKET = auto()
    LIMIT = auto()
    STOP = auto()
    STOP_LIMIT = auto()


class OrderStatus(Enum):
    """Status of an order."""
    PENDING = auto()
    SUBMITTED = auto()
    FILLED = auto()
    PARTIALLY_FILLED = auto()
    REJECTED = auto()
    CANCELLED = auto()


class OperationMode(Enum):
    """System operating mode."""
    LIVE = auto()
    PAPER = auto()
    BACKTEST = auto()


@dataclass
class Bar:
    """OHLCV data point."""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    def __post_init__(self):
        """Ensure timestamp is timezone-aware."""
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)


@dataclass
class MarketState:
    """Current market state for an instrument."""
    symbol: str
    timestamp: datetime
    current_price: float
    bid: float
    ask: float
    volume: float
    volatility: float = 0.0  # Annualized
    bars: List[Bar] = field(default_factory=list)
    
    def __post_init__(self):
        """Ensure timestamp is timezone-aware."""
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)


@dataclass
class Signal:
    """Raw signal generated by an alpha model."""
    symbol: str
    direction: SignalDirection
    strength: float  # 0.0 to 1.0
    timestamp: datetime
    alpha_name: str
    reasoning: str = ""
    
    def __post_init__(self):
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)


@dataclass
class ScoredSignal:
    """Signal after scoring and validation."""
    symbol: str
    direction: SignalDirection
    confidence: float  # 0.0 to 1.0 (after scoring)
    edge: float  # Expected return per unit risk
    timestamp: datetime
    alpha_names: List[str]
    raw_signals: List[Signal] = field(default_factory=list)
    
    def __post_init__(self):
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)


@dataclass
class Position:
    """Current position in an instrument."""
    symbol: str
    quantity: float  # Can be negative for shorts
    entry_price: float
    current_price: float
    timestamp: datetime
    pnl: float = 0.0
    pnl_pct: float = 0.0
    
    def __post_init__(self):
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)
        self._update_pnl()
    
    def _update_pnl(self):
        """Calculate unrealized PnL."""
        if self.quantity != 0:
            self.pnl = self.quantity * (self.current_price - self.entry_price)
            self.pnl_pct = (self.current_price - self.entry_price) / self.entry_price


@dataclass
class Order:
    """Order to be executed."""
    symbol: str
    quantity: float
    order_type: OrderType
    direction: SignalDirection  # LONG or SHORT
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(pytz.UTC))
    order_id: str = ""
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    avg_fill_price: float = 0.0
    
    def __post_init__(self):
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)


@dataclass
class Trade:
    """Completed trade (entry + exit or just entry)."""
    symbol: str
    entry_price: float
    entry_timestamp: datetime
    exit_price: Optional[float] = None
    exit_timestamp: Optional[datetime] = None
    quantity: float = 0.0
    pnl: float = 0.0
    pnl_pct: float = 0.0
    alpha_name: str = ""
    
    def __post_init__(self):
        if self.entry_timestamp.tzinfo is None:
            self.entry_timestamp = pytz.UTC.localize(self.entry_timestamp)
        if self.exit_timestamp and self.exit_timestamp.tzinfo is None:
            self.exit_timestamp = pytz.UTC.localize(self.exit_timestamp)


@dataclass
class PortfolioState:
    """Snapshot of portfolio state."""
    timestamp: datetime
    cash: float
    equity: float
    total_value: float
    positions: Dict[str, Position] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.timestamp.tzinfo is None:
            self.timestamp = pytz.UTC.localize(self.timestamp)
